#关系型数据库配置
[mysql]
host = "127.0.0.1"
port = 3306
database = "dousheng"
username = "root"
password = "123456"
charset = "utf8mb4"
parse_time = true
loc = "Local"

#nosql配置，用于存储每个用户是否对某个视频点赞，以及关注了某个人（主要用于反馈前端情况，比如点了赞后会变成红心
[redis]
host = "127.0.0.1"
port = 6379
database = 0

#记录当前服务器的ip和启动端口号，当前服务器的ip用于生成对应的视频链接地址
[server]
ip = "192.168.1.6"
port = 8080

#用于保存资源的路径，以及用于截图工具的路径（截图工具放在lib目录
[path]

ffmpeg_path = ".\\lib\\ffmpeg.exe"
static_source_path = ".\\static"

# 用于保存视频及图片资源
[minio]
bucket = "dousheng"
video_dir = "videos"
image_dir = "images"
minio_port = 9000


access_key_id = "minioadmin"
secret_access_key = "minioadmin"